# Generated by Django 2.2.1 on 2019-06-09 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('announcements', '0001_initial'),
        ('trooporg', '0014_migrate_member_to_proxy_3')
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trooporg.Member'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Publication'),
        ),
    ]
