# Generated by Django 2.1 on 2018-08-04 18:50

import datetime

from django.db import migrations

DUMMY_NICKNAME = 'Prehistory'


def add_dummy_term(apps, schema_editor):
    today = datetime.date.today()
    yesterday = today - datetime.timedelta(days=1)

    Term = apps.get_model('trooporg', 'Term')
    db_alias = schema_editor.connection.alias

    Term.objects.using(db_alias).create(nickname=DUMMY_NICKNAME, start=yesterday, end=today)


def reverse_add_dummy_term(apps, schema_editor):
    Term = apps.get_model('trooporg', 'Term')
    db_alias = schema_editor.connection.alias

    Term.objects.using(db_alias).filter(nickname=DUMMY_NICKNAME).delete()


def add_terms(apps, schema_editor):
    PatrolMembership = apps.get_model('trooporg', 'PatrolMembership')
    term = apps.get_model('trooporg', 'Term').objects.get(nickname=DUMMY_NICKNAME)
    db_alias = schema_editor.connection.alias

    for p in PatrolMembership.objects.using(db_alias).all():
        p.term = term
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ('trooporg', '0003_auto_20180804_1449'),
    ]

    operations = [
        migrations.RunPython(add_dummy_term, reverse_code=reverse_add_dummy_term),
        migrations.RunPython(add_terms, reverse_code=migrations.RunPython.noop)
    ]
