# Generated by Django 2.1 on 2018-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trooporg', '0006_auto_20180804_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='slug',
            field=models.SlugField(
                help_text='URL Slug that identifies this patrol. Changing this will invalidate any existing urls pointing to this patrol.',
                null=True, unique=True),
        ),
    ]
