# Generated by Django 2.1 on 2018-08-05 15:38
# Perfected by Brian Schubert at roughly the same time.

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Pre-populate each patrol's slug field with its slugified name."""
    Patrol = apps.get_model('trooporg', 'Patrol')
    db_alias = schema_editor.connection.alias

    for pat in Patrol.objects.using(db_alias).all():
        pat.slug = slugify(pat.name)
        pat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trooporg', '0007_patrol_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patrol',
            name='slug',
            field=models.SlugField(help_text='URL Slug that identifies this patrol. Changing this will invalidate any existing urls pointing to this patrol.', unique=True),
        ),
    ]
