# Generated by Django 2.1 on 2018-08-07 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('trooporg', '0010_auto_20180805_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patrolmembership',
            options={'ordering': ('-term__start', 'type')},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'get_latest_by': ('start',), 'ordering': ('-start',)},
        ),
    ]
