# Generated by Django 2.1 on 2018-08-07 21:08

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


def populate_new_member_field(apps, schema_editor):
    """
    Set each patrol membership's transitional scout_new field to be equal
    to the user field of their existing scout field.
    """
    PatrolMembership = apps.get_model('trooporg', 'PatrolMembership')
    db_alias = schema_editor.connection.alias

    for m in PatrolMembership.objects.using(db_alias).all():
        m.scout_new = m.scout.user
        m.save()


def restore_old_member_field(apps, schema_editor):
    """
    Set the user field of each patrol membership's scout field to be equal to
    their transitional scout_new field.
    """
    PatrolMembership = apps.get_model('trooporg', 'PatrolMembership')
    ScoutMembership = apps.get_model('trooporg', 'ScoutMembership')
    db_alias = schema_editor.connection.alias

    for m in PatrolMembership.objects.using(db_alias).all():
        user = m.scout_new
        scout_membership = ScoutMembership.objects.get_or_create(user=user)
        m.scout = scout_membership
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('troop89_auth', '0001_initial'),
        ('trooporg', '0011_auto_20180807_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('troop89_auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='patrol',
            name='members_new',
            field=models.ManyToManyField(through='trooporg.PatrolMembership', to='trooporg.Member'),
        ),
        migrations.AddField(
            model_name='patrolmembership',
            name='scout_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrol_memberships_new', to='trooporg.Member'),
        ),
        migrations.RunPython(
            populate_new_member_field,
            reverse_code=restore_old_member_field,
        )
    ]
