# Generated by Django 2.1 on 2018-08-12 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('trooporg', '0013_migrate_member_to_proxy_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutmembership',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='patrolmembership',
            options={},
        ),
        migrations.DeleteModel(
            name='ScoutMembership',
        ),
    ]
