# Generated by Django 2.1 on 2018-08-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trooporg', '0014_migrate_member_to_proxy_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incumbent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_instances', to='trooporg.Member')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trooporg.Term')),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('precedence', models.PositiveSmallIntegerField(default=0, help_text='Used to help define the order in which similar positions should be displayed. Positions with greater precedence will generally be displayed first.')),
                ('is_adult', models.BooleanField(help_text='Whether or not this position signifies that a member is anadult. This criteria is used for display purposes only.')),
                ('is_leader', models.BooleanField(help_text='Whether or not this position is primarily a leadership role.This criteria is used for partitioning positions for display in some cases.')),
                ('members', models.ManyToManyField(related_name='position_types', through='trooporg.PositionInstance', to='trooporg.Member')),
            ],
            options={
                'ordering': ('precedence',),
            },
        ),
        migrations.AddField(
            model_name='positioninstance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='trooporg.PositionType'),
        ),
        migrations.AlterUniqueTogether(
            name='positioninstance',
            unique_together={('incumbent', 'term', 'type')},
        ),
    ]
