# Generated by Django 2.1 on 2018-08-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trooporg', '0015_add position models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiontype',
            options={'ordering': ('-precedence',)},
        ),
        migrations.AlterField(
            model_name='positioninstance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_instances', to='trooporg.Term'),
        ),
    ]
