# Generated by Django 2.2.1 on 2019-06-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190228_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start', 'title')},
        ),
    ]
